name:                constraint-utilities
version:             0.1.0.0
github:              "githubuser/constraint-utilities"
license:             BSD3
author:              "Jason Adaska"
maintainer:          "jadaska@gmail.com"
copyright:           "2019 JAdaska"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/constraint-utilities#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  constraint-utilities-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraint-utilities

tests:
  constraint-utilities-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - constraint-utilities
